version: "3.8"
services:
  base:
    container_name: Base
    image: ub-base
    env_file: 
      - ./.env
    networks: 
      net_base:
          ipv4_address: 172.120.30.2
networks: 
  net_base:
      ipam: 
          driver: default
          config: 
              - subnet: 172.120.30.0/24 
